import moment from 'moment';

const APP_CONSTANTS = {
    FILTER_BY: {
        NON_STOP: 'non-stop',
        ALL: 'all'
    },
    SORT_BY: {
        DEPARTURE: 'departure',
        DURATION: 'duration',
        PRICE: 'price'
    },
    FLIGHTS: [
        {
            id: 1,
            FLIGHT_ID: "3M 234",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 7,
            D_TIME: moment('2020-03-12 13:00:00').format('LT'),
            A_TIME: moment('2020-03-12 13:00:00').add(7, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "direct",
            COST: 8234,
            COST_WITH_RESCHEDULING: 10234,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: false,
            IS_FLEXI: true
        },
        {
            id: 0,
            FLIGHT_ID: "6E 171",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 3.5,
            D_TIME: moment().format('LT'),
            A_TIME: moment().add(3.5, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "non-stop",
            COST: 2350,
            COST_WITH_RESCHEDULING: 3024,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: true,
            IS_FLEXI: false
        },
        {
            id: 2,
            FLIGHT_ID: "9N 723",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 11.5,
            D_TIME: moment('2020-03-12 18:32:00').format('LT'),
            A_TIME: moment('2020-03-12 18:32:00').add(11.5, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "direct",
            COST: 43234,
            COST_WITH_RESCHEDULING: 49224,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: false,
            IS_FLEXI: false
        },
        {
            id: 3,
            FLIGHT_ID: "9N 723",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 11.5,
            D_TIME: moment('2020-03-12 18:32:00').format('LT'),
            A_TIME: moment('2020-03-12 18:32:00').add(11.5, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "direct",
            COST: 32234,
            COST_WITH_RESCHEDULING: 35224,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: false,
            IS_FLEXI: false
        },
        {
            id: 4,
            FLIGHT_ID: "9N 723",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 11.5,
            D_TIME: moment('2020-03-12 18:32:00').format('LT'),
            A_TIME: moment('2020-03-12 18:32:00').add(11.5, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "direct",
            COST: 3234,
            COST_WITH_RESCHEDULING: 4224,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: false,
            IS_FLEXI: false
        },
        {
            id: 5,
            FLIGHT_ID: "9N 723",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 3.5,
            D_TIME: moment().format('LT'),
            A_TIME: moment().add(3.5, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "direct",
            COST: 43234,
            COST_WITH_RESCHEDULING: 49224,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: false,
            IS_FLEXI: false
        },
        {
            id: 6,
            FLIGHT_ID: "9N 723",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 1,
            D_TIME: moment('2020-03-12 18:32:00').format('LT'),
            A_TIME: moment('2020-03-12 18:32:00').add(11.5, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "non-stop",
            COST: 43234,
            COST_WITH_RESCHEDULING: 49224,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: false,
            IS_FLEXI: false
        },
        {
            id: 7,
            FLIGHT_ID: "9N 723",
            DATE: moment('2016-03-12 13:00:00').format(),
            DURATION: 11.5,
            D_TIME: moment('2020-03-12 18:32:00').format('LT'),
            A_TIME: moment('2020-03-12 18:32:00').add(11.5, 'hours').format('LT'),
            FROM: "DELHI",
            TO: "MUMBAI",
            TYPE: "direct",
            COST: 43234,
            COST_WITH_RESCHEDULING: 49224,
            SALE_ACTIVE: true,
            CHECKIN_BAGGAGE: 15,
            HAND_BAGGAGE: 7,
            FUEL_CHARGE: 400,
            CUTE_CHARGE: 50,
            RCS_PROVISION: 50,
            AIRPORT_SECURITY_FEE: 175,
            PASSENGER_SERVICE_FEE: 80,
            CGST: 62,
            SGST: 62,
            IS_REVISED: true,
            IS_SELECTED: false,
            IS_FLEXI: false
        }
    ]
}

export default APP_CONSTANTS;